#!/usr/bin/env bash
# Source install/update for the single-user desktop app.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

npm install
# Some clean hosts have npm configured to skip lifecycle scripts. Make the two
# runtime native/binary packages explicit so a source install cannot pass tests
# and then fail at `electron .` because `node_modules/electron/path.txt` is
# missing.
npm rebuild electron node-pty
uv venv --python 3.13
uv pip install -e '.[dev]'

mkdir -p "$HOME/.local/share/applications"
sed "s#__PROJECT_ROOT__#$REPO#g" scripts/aico.desktop >"$HOME/.local/share/applications/aico.desktop"

if [ "${AICO_INSTALL_CONTEXT_HOOKS:-0}" = "1" ]; then
  scripts/aico-install-context-hooks.sh
else
  echo "Skipping optional TUI context hooks. Set AICO_INSTALL_CONTEXT_HOOKS=1 to install them."
fi

if command -v gsettings >/dev/null 2>&1; then
  scripts/aico-hotkeys.sh install || true
fi

# Electron now runs with the OS sandbox enabled (webPreferences.sandbox: true).
# On kernels with apparmor_restrict_unprivileged_userns=1 (Ubuntu 24.04+) that
# sandbox can't create its user namespace unless this checkout's Electron binary
# is granted `userns` via an AppArmor profile. Generate a path-correct profile
# (the committed one hard-codes a path) and load it. Never aborts the install.
install_apparmor() {
  command -v apparmor_parser >/dev/null 2>&1 || return 0
  local electron_bin="$REPO/node_modules/electron/dist/electron"
  [ -x "$electron_bin" ] || return 0
  if aa-status 2>/dev/null | grep -q "$electron_bin"; then
    echo "AppArmor: aico-electron profile already loaded."
    return 0
  fi
  local profile
  profile="$(mktemp)"
  cat >"$profile" <<EOF
# Grants unprivileged user-namespace creation so Electron's sandbox initializes
# on kernels with apparmor_restrict_unprivileged_userns=1. Path-matched to this
# checkout's Electron binary; regenerated by aico-install.sh.
abi <abi/4.0>,
include <tunables/global>

profile aico-electron $electron_bin flags=(unconfined) {
  userns,
  include if exists <local/aico-electron>
}
EOF
  if [ -t 0 ] && command -v sudo >/dev/null 2>&1; then
    echo "AppArmor: installing the Electron sandbox profile (needs sudo)..."
    if sudo cp "$profile" /etc/apparmor.d/aico-electron &&
      sudo apparmor_parser -r /etc/apparmor.d/aico-electron; then
      echo "AppArmor: profile loaded."
    else
      echo "AppArmor: install failed; load it manually (see below)."
    fi
  else
    echo "AppArmor: non-interactive shell; install the generated profile manually:"
    echo "  sudo cp $profile /etc/apparmor.d/aico-electron"
    echo "  sudo apparmor_parser -r /etc/apparmor.d/aico-electron"
    return 0
  fi
  rm -f "$profile"
}
install_apparmor || true

cat <<'EOF'
Aico source install complete.

Launch:
  scripts/aico-launch.sh

Stop:
  scripts/aico-stop.sh
EOF
