#!/usr/bin/env bash
# Source install/update for the single-user desktop app.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

npm install
# Some clean hosts have npm configured to skip lifecycle scripts. Make the
# runtime native package explicit, then verify Electron's downloaded binary
# exists; if the upstream installer leaves only package files behind, fetch the
# zip with @electron/get and extract it with Python's zipfile.
npm rebuild electron node-pty

ensure_electron_binary() {
  local electron_dir="node_modules/electron"
  local platform_path="electron"
  case "$(node -p 'process.platform')" in
    win32) platform_path="electron.exe" ;;
    darwin) platform_path="Electron.app/Contents/MacOS/Electron" ;;
  esac

  if [ -f "$electron_dir/path.txt" ] && [ -e "$electron_dir/dist/$platform_path" ]; then
    return 0
  fi

  echo "Electron: fetching runtime binary..."
  local info zip_path
  info="$(
    node <<'NODE'
const { downloadArtifact } = require('@electron/get')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const electronDir = path.join(process.cwd(), 'node_modules', 'electron')
const version = require(path.join(electronDir, 'package.json')).version
const platform = process.env.ELECTRON_INSTALL_PLATFORM || process.env.npm_config_platform || process.platform
const arch = process.env.ELECTRON_INSTALL_ARCH || process.env.npm_config_arch || process.arch

downloadArtifact({
  version,
  artifactName: 'electron',
  platform,
  arch,
  checksums: require(path.join(electronDir, 'checksums.json')),
  cacheRoot: fs.mkdtempSync(path.join(os.tmpdir(), 'aico-electron-cache-')),
})
  .then((zip) => console.log(JSON.stringify({ zip })))
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
NODE
  )"
  zip_path="$(python3 -c 'import json,sys; print(json.loads(sys.stdin.read())["zip"])' <<<"$info")"
  python3 - "$zip_path" "$electron_dir/dist" <<'PY'
import shutil
import sys
import zipfile
from pathlib import Path

zip_path = Path(sys.argv[1])
dist = Path(sys.argv[2])
shutil.rmtree(dist, ignore_errors=True)
dist.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(zip_path) as archive:
    archive.extractall(dist)
PY
  printf '%s' "$platform_path" >"$electron_dir/path.txt"
  chmod +x "$electron_dir/dist/$platform_path" 2>/dev/null || true
  test -e "$electron_dir/dist/$platform_path"
}

ensure_electron_binary

configure_electron_suid_sandbox() {
  [ "$(node -p 'process.platform')" = "linux" ] || return 0
  local sandbox="$REPO/node_modules/electron/dist/chrome-sandbox"
  [ -e "$sandbox" ] || return 0
  if [ "$(stat -c '%u:%a' "$sandbox" 2>/dev/null || true)" = "0:4755" ]; then
    return 0
  fi
  if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
    echo "Electron: configuring chrome-sandbox helper..."
    sudo chown root:root "$sandbox"
    sudo chmod 4755 "$sandbox"
  else
    echo "Electron: chrome-sandbox helper needs root ownership for sandboxed launches:"
    echo "  sudo chown root:root $sandbox"
    echo "  sudo chmod 4755 $sandbox"
  fi
}

configure_electron_suid_sandbox
uv venv --python 3.13
uv pip install -e '.[dev]'

mkdir -p "$HOME/.local/share/applications"
sed "s#__PROJECT_ROOT__#$REPO#g" scripts/aico.desktop >"$HOME/.local/share/applications/aico.desktop"

if [ "${AICO_INSTALL_CONTEXT_HOOKS:-0}" = "1" ]; then
  scripts/aico-install-context-hooks.sh
else
  echo "Skipping optional TUI context hooks. Set AICO_INSTALL_CONTEXT_HOOKS=1 to install them."
fi

if command -v gsettings >/dev/null 2>&1; then
  scripts/aico-hotkeys.sh install || true
fi

# Electron now runs with the OS sandbox enabled (webPreferences.sandbox: true).
# On kernels with apparmor_restrict_unprivileged_userns=1 (Ubuntu 24.04+) that
# sandbox can't create its user namespace unless this checkout's Electron binary
# is granted `userns` via an AppArmor profile. Generate a path-correct profile
# (the committed one hard-codes a path) and load it. Never aborts the install.
install_apparmor() {
  command -v apparmor_parser >/dev/null 2>&1 || return 0
  local electron_bin="$REPO/node_modules/electron/dist/electron"
  [ -x "$electron_bin" ] || return 0
  if aa-status 2>/dev/null | grep -q "$electron_bin"; then
    echo "AppArmor: aico-electron profile already loaded."
    return 0
  fi
  local profile
  profile="$(mktemp)"
  cat >"$profile" <<EOF
# Grants unprivileged user-namespace creation so Electron's sandbox initializes
# on kernels with apparmor_restrict_unprivileged_userns=1. Path-matched to this
# checkout's Electron binary; regenerated by aico-install.sh.
abi <abi/4.0>,
include <tunables/global>

profile aico-electron $electron_bin flags=(unconfined) {
  userns,
  include if exists <local/aico-electron>
}
EOF
  if [ -t 0 ] && command -v sudo >/dev/null 2>&1; then
    echo "AppArmor: installing the Electron sandbox profile (needs sudo)..."
    if sudo cp "$profile" /etc/apparmor.d/aico-electron &&
      sudo apparmor_parser -r /etc/apparmor.d/aico-electron; then
      echo "AppArmor: profile loaded."
    else
      echo "AppArmor: install failed; load it manually (see below)."
    fi
  else
    echo "AppArmor: non-interactive shell; install the generated profile manually:"
    echo "  sudo cp $profile /etc/apparmor.d/aico-electron"
    echo "  sudo apparmor_parser -r /etc/apparmor.d/aico-electron"
    return 0
  fi
  rm -f "$profile"
}
install_apparmor || true

cat <<'EOF'
Aico source install complete.

Launch:
  scripts/aico-launch.sh

Stop:
  scripts/aico-stop.sh
EOF
